
alias gen-cscope='find . -iname '\''*.c'\'' -o -iname '\''*.cpp'\'' -o -iname '\''*.cc'\'' -o -iname '\''*.h'\'' -o -iname '\''*.hpp'\'' > cscope.files && cscope -b -i cscope.files -f cscope.out'
alias gen-tags='ctags -R --c++-kinds=+p --fields=+iaS --extra=+q'
alias remove-whitespace='sed -e '\''s/[[:blank:]]\+$//'\'' -i'
alias remove-ws-in-last-commit= 'for f in `git show --name-only --pretty=""`; do echo $f; remove-whitespace $f; done'
