#!/usr/bin/env bash
#
usage() {
    echo "Invalid syntax:"
    echo "$0 vm"
    echo "  vm - connect to local vm: shiva-deb-1"
} 

if [ 1 -ne $# ]; then
    usage
    exit
fi

if [ "vm" = $1 ]; then
    ssh -p 2222 shiva@127.0.0.1  # expect port-forwarding to be setup
fi
