#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null
GIT_REPO_BASE="$(dirname "$SCRIPTPATH")"

dest_dotvim="~/.vim"
if [ -d ${dest_dotvim} ]; then
  # make a copy 
  echo "Making a backup of existing .vim"
  mv ${dest_dotvim} ~/dotvim.bkp
fi

dest_vimrc="~/.vimrc"
if [ -f ${dest_vimrc} ]; then
  # make a copy
  echo "Making a backup of existing .vimrc"
  mv ${dest_vimrc} ~/vimrc.bkp
fi

echo "Making symlink for .vimrc"
ln -s ${GIT_REPO_BASE}/nix-cfg/vimrc ~/.vimrc

