#!/bin/bash

# vars
RSYNC_CMD="rsync"

# password-less ssh expected (setup keys)
DNS323_HOST="10.0.1.110"
DNS323_USER="bkpuser"
PASSWD_FILE=~/.ssh/dns323_rsync_passwd

SRC_MOVIES="/Users/shiva/Movies"
DEST_MOVIES="movies"

SRC_PHOTOS="/Volumes/M5-2/Pictures/lr-photos"
DEST_PHOTOS="photos/raw"

SRC_IPHONEPHOTOS="/Volumes/M5-2/Pictures/iphone"
DEST_IPHONEPHOTOS="photos/iphone"

SRC_LIGHTROOM="/Users/shiva/Pictures/Lightroom"
DEST_LIGHTROOM="photos/Lightroom"

# A pretend Python dictionary with bash 3 
sync_dirs=( "${SRC_MOVIES}:${DEST_MOVIES}"
            "${SRC_PHOTOS}:${DEST_PHOTOS}"
            "${SRC_IPHONEPHOTOS}:${DEST_IPHONEPHOTOS}"
            "${SRC_LIGHTROOM}:${DEST_LIGHTROOM}" )

# Check ssh connection
#echo "Testing ssh connection ..."
#ssh -T ${DNS323_USER}@${DNS323_HOST} || die("Unable to connect to $DNS323_HOST via ssh")

echo "Starting rsync ... "
for d in "${sync_dirs[@]}" ; do
    SRC=${d%%:*}
    DEST=${d#*:}

    printf "%s syncs to mac-rsync/%s.\n" "$SRC" "$DEST"
    
    #printf "$RSYNC_CMD -r ${SRC}/* rsync://${DNS323_USER}@${DNS323_HOST}:873/mac-rsync/${DEST}/"
    $RSYNC_CMD --password-file=${PASSWD_FILE} -azhO --progress --stats --no-perms ${SRC}/* rsync://${DNS323_USER}@${DNS323_HOST}:873/mac-rsync/${DEST}/ 
done

die() { 
    echo "$@" 1>&2 ; exit 1; 
}
