" Forget being compatible with good ol' vi
set nocompatible

"set t_Co=256
"color jellybeans

set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

" Get that filetype stuff happening
filetype on
filetype plugin on
filetype indent on

" Turn on that syntax highlighting
syntax enable

" Turn on omnicomplete
set omnifunc=syntaxcomplete#Complete

" Why is this not a default
set hidden

" Don't update the display while executing macros
set lazyredraw

" At least let yourself know what mode you're in
set showmode

" Enable enhanced command-line completion. Presumes you have compiled
" with +wildmenu.  See :help 'wildmenu'
set wildmenu

" Let's make it easy to edit and source vimrc
nmap <silent> ,ev :e $MYVIMRC<cr>
nmap <silent> ,sv :so $MYVIMRC<cr>

set tabstop=4
set shiftwidth=4
set expandtab

" Set default undo locations"
set dir=~/.vimswap//,/var/tmp//,/tmp//,.

call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

execute pathogen#infect()
